on:
  push:
    branches: [ main ]
permissions:
  contents: read
name: 🚀 Tests and Deploy website on push
jobs:
  # Continous integration
  tests:
    runs-on: ubuntu-latest

    name: Continous integration

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath

      - name: Install Composer dependencies
        run: composer install --prefer-dist

      - name: Copy environment file
        run: |
          cp .env.example .env
         
    
      - name: Generate app key
        run: php artisan key:generate
        
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
        
  # Continous deployment/development
  web-deploy:
    needs: tests
    runs-on: ubuntu-latest
    name: 🚀 Continous Deployment

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extension-csv: mbstring, bcmath, mysqli

      - name: Restore composer cache
        uses: actions/cache@v2
        with:
         path: vendor
         key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
         restore-keys: |
            ${{ runner.os }}-php-
            
      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist
    
      - name: Copy environment file
        run: |
          cp .env.example .env
          

      - name: Generate app key
        run: php artisan key:generate

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
              server: ${{ secrets.FTP_SERVER }}
              username: ${{ secrets.FTP_USER }}
              password: ${{ secrets.FTP_PASS }}
              protocol: ftps 
              port: ${{ secrets.FTP_PORT }}
              server-dir: /public_html/
